server:
  port: 8080


logging:
  level:
    root: WARN
    at.fhtw.tourplanner: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: OFF

spring:
  application:
    name: tourplanner
  datasource:
    url: jdbc:postgresql://localhost:5432/tourplanner
    username: touruser
    password: tourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # change to false if you don't want to see SQL statements in the logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  frontend:
    url: http://localhost:3000,http://localhost:4173

  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 3600000 # 1 hour
