services:
  postgres:
    image: postgres:16
    container_name: tourplanner-db
    restart: always
    environment:
      POSTGRES_DB: tourplanner
      POSTGRES_USER: touruser
      POSTGRES_PASSWORD: tourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: